# docker-compose.yml
# ----------------------------------------------------
# Sets up the Flask API with a PostgreSQL backend.
# Enables local testing and scaling using Docker Compose.
# Uses a shared .env file to securely load credentials.
# ----------------------------------------------------

version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:5000"  # Maps container port 5000 to host port 5000
    depends_on:
      - db           # Ensures the database starts before the API
    env_file:
      - .env         # Loads environment variables from .env file

  db:
    image: postgres:14
    env_file:
      - .env         # Loads DB name, user, password from .env file
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data

volumes:
  pgdata:  # Named volume for database storage
